### ISSUE TITLE
De Lijn stopped working

### ISSUE THREAD

**Issue by Meerkater** [bollewolle/delijn-card#4] opened 2020-04-19 18:10 UTC
I'm using delijn-card for more than a week and everything worked fine. After the lastest Home Assistant update it stopped working and always shows 'No passages anymore today'.

**Comment by bollewolle** [comment] 2020-04-27 13:44
Is this still an issue or has it been resolved by now? Could you provide me de stop_id that you are using for De Lijn so I can look into it? Because my 3 stop_id's seem to be working, so I'd need to know the one you're using so I can find out what the issue is.
Thanks!

**Comment by Meerkater** [comment] 2020-04-27 16:39
This is already resolved.

Op ma 27 apr. 2020 15:44 schreef Bram Goolaerts <notifications@github.com>:

**Comment by bollewolle** [comment] 2020-04-27 17:10
Alright, will close the issue then.

Thanks.

**Closed as completed by bollewolle** 2020-04-27 17:10 UTC
